### ISSUE TITLE
Output of dropout notebook (assignment 2) seems wrong

### ISSUE THREAD

**Issue by soarerz** [mantasu/cs231n#15]
In https://github.com/mantasu/cs231n/blob/master/assignment2/Dropout.ipynb, the outputs under "Dropout: Forward Pass" seem wrong.
- For inverted dropout, mean of train time output and mean of input should be roughly the same. This is not the case there.
- As p is the probability of keeping a node, "Fraction of train-time output set to zero" should be around 1 - p. This is not the case there.

As a result, the pics under "Regularization Experiment" maybe wrong. 
- In my notebook, the delta of train accuracy between no-dropout and dropout seems to be quite big; see attachment.
![image](https://github.com/mantasu/cs231n/assets/4777120/5ce19e57-dbf0-467f-85b9-03c1ccd280db)

I checked your implementation of dropout forward/backward layer and they seem fine. Perhaps it's worth rerunning the notebook?

p.s. thanks for sharing this repo! It's been helpful to cross check answers

**Comment by mantasu** [comment]
Hey, thanks for pointing this out! Yeah, I got the same curves after rerunning. Perhaps it's a change from an older version or something just went wrong with the last run 😅 Thanks again and glad the repo is helpful!
