### ISSUE TITLE
Can I run assignment3 locally?

### ISSUE THREAD

**Issue by ge1mina023** [mantasu/cs231n#4]
Using my MacBook Pro M1

**Comment by mantasu** [comment]
Yes, you will need GPU acceleration which is supported by PyTorch for M1 chips as well. You can install PyTorch by following this guide https://developer.apple.com/metal/pytorch/. Then just install the requirements:
```bash
pip install -r assignment3/requirements.txt
```

**Comment by ge1mina023** [comment]
thanks~

**Comment by ge1mina023** [comment]
What should I do additionally?  Only comment out the code about google colab?

**Comment by mantasu** [comment]
You should also do the following changes in the files that actually use GPU acceleration:
1. In `Generative_Adversarial_Networks.ipynb`, whenever `.type(dtype)` is called, change that to `.to(device="mps")`
2. In `Self_Supervised_Learning.ipynb` change the final line in the 4th code cell:
    ```python
    # device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
    ```

**Comment by ge1mina023** [comment]
Is that all I need to do?

**Comment by mantasu** [comment]
I can't confirm since I don't have Apple M1. It should be all but if you encounter any issues let me know.

**Comment by ge1mina023** [comment]
> I can't confirm since I don't have Apple M1. It should be all but if you encounter any issues let me know.

thanks a lot~
