### ISSUE TITLE
Assignment2/cs231n/layers.py line 482: "np.random.rand" rather than "np.random.randn"

### ISSUE THREAD

**Issue by nhattan417** [mantasu/cs231n#7]
[Link to the issue](https://github.com/mantasu/cs231n/blob/3a92e8be88958385222c989f430b090df1c7f87b/assignment2/cs231n/layers.py#L482)

Hi, I think it should be "np.random.rand" instead of "np.random.randn" on line 482 as "rand" will return numbers from uniform distribution of [0; 1) whereas "randn" will return numbers from standard normal distribution. In the case of implementing dropout, the function "rand" seems to be more reasonable. (p/s: sample code from classnote of cs231n also use "np.random.rand"; please check the [link](https://cs231n.github.io/neural-networks-2/#reg), dropout part).

Please correct me if I am wrong. Thank you!

**Comment by mantasu** [comment]
Yup `rand` should be used, thanks, I'll fix!
